language: python

python:
  - 2.7
  - 3.8
  - 3.9

before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)

before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install qrcode
  - pip install pyTelegramBotAPI
script:
  pytest

services:
  docker

branches:
  only:
    - main
