language: python
sudo: required

python:
  - 3.8
  - 3.9

before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)

before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install qrcode
  - pip install pyTelegramBotAPI
  - pip install black
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh #installed heroku CLI
  - docker login --username='gen.hort54@gmail.com' --password='82f37e21-4814-4e99-ad11-367ca38286d5' registry.heroku.com
  - docker build -t galaxy13/telegramqrbot .
  - black botMain.py --check
  - black libraries/qr_make.py --check
  - black libraries/url.py --check
  - black tests/test_url_validation.py --check

script:
  docker run galaxy13/telegram_bot-docker.test python pytest

after_script:
  - bash docker_hub_push
  - docker tag galaxy13/telegram_bot-Docker.test registry.heroku.com/telegramqrbot/web
  - docker push registry.heroku.com/telegramqrbot/web

services:
  docker

branches:
  only:
    - heroku

deploy:
  provider: script
  api_key:
    '82f37e21-4814-4e99-ad11-367ca38286d5'
  script:
    heroku container:release web --app telegramqrbot
  on: heroku
