language: python
sudo: required

python:
  - 3.8
  - 3.9

before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)

before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install qrcode
  - pip install pyTelegramBotAPI
  - pip install black
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh #installed heroku CLI
  - docker login --username=_ --password=$(heroku auth:token) registry.heroku.com
  - black botMain.py --check
  - black libraries/qr_make.py --check
  - black libraries/url.py --check
  - black tests/test_url_validation.py --check

script:
  pytest

services:
  docker

branches:
  only:
    - heroku

deploy:
  provider: script
  script:
    heroku container:release web --app telegramqrbot
