language: python
sudo: required

python:
  - 3.8
  - 3.9

before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
  - travis encrypt MY_SECRET_ENV=super_secret -r Galaxy13/telegram_bot-Docker.test --add deploy.api_key

before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install qrcode
  - pip install pyTelegramBotAPI
  - pip install black
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh #installed heroku CLI
  - docker login --username='gen.hort54@gmail.com' --password='82f37e21-4814-4e99-ad11-367ca38286d5' registry.heroku.com
  - black botMain.py --check
  - black libraries/qr_make.py --check
  - black libraries/url.py --check
  - black tests/test_url_validation.py --check
  - gem install travis
  - travis encrypt '82f37e21-4814-4e99-ad11-367ca38286d5' --add deploy.api_key

script:
  pytest

services:
  docker

branches:
  only:
    - heroku

deploy:
  provider: script
  api_key:
    ''
  script:
    heroku container:release web --app telegramqrbot
  on: heroku
