language: python

python:
  - 3.8
  - 3.9

before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
  - black --check

before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install qrcode
  - pip install pyTelegramBotAPI
  - pip install black

script:
  pytest

services:
  docker

branches:
  only:
    - main
